# Site settings
title: SMAC Group
subtitle: "Statistical Methods, Applications &amp; Computing Group"
name: SMAC Group
email: contact@smac-group.com
description: > # this means to ignore newlines until "baseurl:"
  Statistical Methods, Applications &amp; Computing Group 
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://smac-group.com" # the base hostname & protocol for your site
twitter_username: smac-group
github_username: smac-group

cover: "assets/images/site/goat-c.png"
#logo: "assets/logo.png"


# Build settings
permalink: "/:categories/:title"

markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

kramdown:
  input: GFM
  syntax_highlighter: rouge 

social:
  - name: Contact
    icon: envelope-o
    username: contact@smac-group.com
    url: mailto:contact@smac-group.com
    desc: E-Mail Us
    share: false
	
  - name: GitHub
    icon: github
    username: SMAC-Group
    url: https://github.com/SMAC-Group
    desc: Fork Our Projects on GitHub
    share: false