# Site settings
title: SMAC Group
subtitle: "Statistical Methods, Applications &amp; Computing Group"
name: SMAC Group
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Statistical Methods, Applications &amp; Computing Group 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "http://smac-group.com" # the base hostname & protocol for your site
github_username:  smac-group

# Site map plugin
# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"
